name: Auto Label PR Size

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v2

      - name: Get PR diff and calculate size
        id: calculate_size
        run: |
          # Get the number of lines changed in the PR
          CHANGED_LINES=$(git diff --shortstat ${{ github.event.before }} ${{ github.sha }} | grep -o '[0-9]\+ inserted' | awk '{print $1}')
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          
          echo "Changed files: $CHANGED_FILES"
          echo "Changed lines: $CHANGED_LINES"

          # Based on lines changed, set the size
          if [ "$CHANGED_LINES" -le 50 ]; then
            echo "Labeling as tiny"
            echo "::set-output name=label::size: tiny"
          elif [ "$CHANGED_LINES" -le 200 ]; then
            echo "Labeling as small"
            echo "::set-output name=label::size: small"
          elif [ "$CHANGED_LINES" -le 500 ]; then
            echo "Labeling as medium"
            echo "::set-output name=label::size: medium"
          elif [ "$CHANGED_LINES" -le 1000 ]; then
            echo "Labeling as large"
            echo "::set-output name=label::size: large"
          else
            echo "Labeling as huge"
            echo "::set-output name=label::size: huge"
          fi

      - name: Apply the label
        uses: github-actions/github-action-labeler@v2
        with:
          repo-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          label: ${{ steps.calculate_size.outputs.label }}
